### ISSUE TITLE
Date Selection Unresponsive

### ISSUE THREAD

**Issue by drewlar** [cse110-sp24-group9/warmup-exercise#1]
When I try to click on another day, I don't have any indication that the day has been selected and only the current day is selected. 
<img width="1552" alt="image" src="https://github.com/cse110-sp24-group9/warmup-exercise/assets/130115948/0911d53d-ac46-4ad1-a743-f8e80f49293f">

**Comment by andrewcomputsci2019** [comment]
fixed in #2
